- package-lock.json
- src/app/auth/auth.component.html
- src/app/auth/auth.component.scss
- src/index.html
- src/styles.scss
Added global styles from stylesheet, created squac color variables, and formatted login page.
> Login page

- src/app/channel-groups/channel-groups-view/channel-groups-view.component.html
- src/app/channel-groups/channel-groups-view/channel-groups-view.component.ts
- src/app/metrics/metrics-edit/metrics-edit.component.html
- src/app/metrics/metrics-view/metrics-view.component.html
- src/app/metrics/metrics-view/metrics-view.component.ts
- src/styles.scss
Styling fixes for buttons in headers, reduced tags for selection colors, added an edit button to metric and channel group pages.
> Added edit buttons for metric and channel group

- src/app/channel-groups/channel-groups-edit/channel-groups-edit.component.html
- src/app/channel-groups/channel-groups-edit/channel-groups-edit.component.scss
- src/app/channel-groups/channel-groups-edit/channel-groups-edit.component.ts
- src/app/channel-groups/channel-groups-edit/channel-groups-filter/channel-groups-filter.component.html
- src/app/channel-groups/channel-groups-edit/channel-groups-filter/channel-groups-filter.component.scss
- src/app/channel-groups/channel-groups-view/channel-groups-view.component.ts
- src/app/channel-groups/channel-groups.component.ts
- src/app/shared/map/map.component.scss
- src/environments/environment.ts
Add query by lat lon box on map, styling fix for cg edit page, routing fix for new channel groups
> Map lat lon request

- Dockerfile
- docker-compose.yml
- package.json
More convenient than deailing with node and nvm
> Dockerized squac

- src/app/features/channel-groups/components/channel-groups-edit/channel-groups-edit.component.ts
- src/app/features/channel-groups/components/channel-groups-edit/channel-groups-filter/channel-groups-filter.component.html
- src/app/features/channel-groups/components/channel-groups-edit/channel-groups-filter/channel-groups-filter.component.ts
Fix channel regex for filters, make the remove channel filter conditions AND.
> A few channel group filtering fixes

- src/app/core/services/squacapi.service.ts
- src/app/features/channel-groups/components/channel-groups-edit/channel-groups-edit.component.html
- src/app/features/channel-groups/components/channel-groups-edit/channel-groups-edit.component.scss
- src/app/features/channel-groups/components/channel-groups-edit/channel-groups-edit.component.ts
- src/app/features/channel-groups/services/channel-groups.service.ts
- src/app/features/metrics/metrics-edit/metrics-edit.component.html
- src/app/features/metrics/metrics-edit/metrics-edit.component.ts
- src/styles.scss
Add a button to remove channel group in the edit page, refactor popup function and style, fix edit metric page cancel, fix bug with saving private channel groups.
> Add ability to remove channel groups in Squac

- src/app/app-routing.module.ts
- src/app/features/metrics/components/metrics-view/metrics-view.component.html
- src/app/features/metrics/components/metrics-view/metrics-view.component.scss
> closes #159

- src/app/features/widgets/pipes/measurement.pipe.spec.ts
- src/app/features/widgets/pipes/measurement.pipe.ts
> fix measurement pipe to actually show recent, more tests

- src/app/core/services/squacapi.service.ts
- src/app/features/dashboards/components/dashboard-detail/dashboard-detail.component.html
> Kyla m/issue138

- src/app/features/dashboards/components/dashboard-detail/dashboard-detail.component.html
- src/app/features/dashboards/components/dashboard-detail/dashboard-detail.component.scss
- src/app/features/widgets/components/widget-edit/widget-edit-entry/widget-edit-entry.component.ts
- src/app/features/widgets/components/widget-edit/widget-edit.component.ts
- src/app/features/widgets/components/widget-types/timeseries/timeseries.component.html
- src/app/features/widgets/components/widget-types/timeseries/timeseries.component.ts
- src/app/features/widgets/components/widgets/widgets.component.ts
- src/app/features/widgets/services/measurements.service.ts
- indicate share status
- fix view bug safari
- fix dates
- utc on timeline
> Dashboardfix

- src/app/features/widgets/components/widget-types/timeseries/timeseries.component.ts
representing gaps in data and made it so channels with no data are not shown
> Timeseries updates

- src/app/features/monitors/components/monitor-edit/monitor-edit.component.html
- src/app/features/monitors/components/monitor-edit/monitor-edit.component.ts
- src/app/features/monitors/components/monitor-view/monitor-view.component.html
- src/app/features/monitors/components/monitor-view/monitor-view.component.ts
- src/environments/environment.ts
Fixes #298, Fixes #296, Fixes #295 
Fixes in alarm showing incorrectly
Adds all option
> Monitorbugs

- src/app/features/channel-groups/components/channel-groups-edit/channel-groups-filter/channel-groups-filter.component.html
- src/app/features/channel-groups/components/channel-groups-edit/channel-groups-filter/channel-groups-filter.component.ts
> Kyla-m/issue304

- src/app/core/models/channel-group.ts
> fix sharing for groups

- src/app/features/channel-group/components/channel-group-view/channel-group-view.component.html
- src/app/features/channel-group/components/channel-group-view/channel-group-view.component.ts
- src/app/features/dashboard/components/dashboard-view/dashboard-view.component.ts
- src/app/features/metric/components/metric-view/metric-view.component.ts
Add owner to metric table
Add sharing settings to channel group table
> add owner to metric table and sharing settings to channel group

- projects/squac-ui/src/app/core/cacheable-route-patterns.constant.ts
- projects/squac-ui/src/app/core/services/auth.service.ts
- projects/squac-ui/src/app/core/services/local-storage.service.ts
- projects/squac-ui/src/app/features/user/components/organization-detail/organization-detail.component.ts
- projects/squac-ui/src/app/features/user/components/user-edit/user-edit.component.html
- projects/squac-ui/src/app/features/user/components/user-edit/user-edit.component.ts
- projects/squac-ui/src/app/shared/components/table-view/table-view.component.ts
Fixes registration failure caused by password validator
> Invite error

- projects/squac-ui/src/app/app.module.ts
- projects/squac-ui/src/app/features/channel-group/channel-group.module.ts
- projects/squac-ui/src/app/features/dashboard/components/dashboard-detail/channel-filter/channel-filter.component.ts
- projects/squac-ui/src/app/features/dashboard/components/dashboard-detail/dashboard-detail.component.html
- projects/squac-ui/src/app/features/dashboard/components/dashboard-detail/dashboard-detail.component.scss
- projects/squac-ui/src/app/features/dashboard/components/dashboard-detail/data-type-selector/data-type-selector.component.html
- projects/squac-ui/src/app/features/dashboard/components/widget-detail/widget-detail.component.html
- projects/squac-ui/src/app/features/dashboard/components/widget-main/widget-main.component.ts
- projects/squac-ui/src/app/shared/components/date-select/date-select.component.html
- projects/squac-ui/src/app/shared/shared.module.ts
- projects/squac-ui/src/styles/material.scss
- projects/widgets/src/lib/services/widget-manager.service.ts
- projects/widgets/src/lib/shared/components/generic-widget.component.ts
- projects/widgets/src/lib/shared/utils/comparators.utils.ts
- projects/widgets/src/lib/shared/utils/index.ts
- projects/widgets/src/lib/widget-types/calendar/calendar.component.ts
- projects/widgets/src/lib/widget-types/map/map.component.ts
- projects/widgets/src/lib/widget-types/parallel-plot/parallel-plot.component.ts
- projects/widgets/src/lib/widget-types/scatter-plot/scatter-plot.component.ts
- projects/widgets/src/lib/widget-types/tabular/tabular.component.ts
- projects/widgets/src/lib/widget-types/tabular/utils.ts
- projects/widgets/src/lib/widget-types/timechart/timechart.component.ts
- projects/widgets/src/lib/widget-types/timeline/timeline.component.ts
- fixes channels resetting on dashboard
- change dashboard header back to original style
- improve responsiveness when toggling on dashboard
- fix map not loading initially due to race condition
> Fix channels loading

- projects/widgets/src/lib/widget-types/tabular/tabular.component.ts
> fix table widget using channel measurements without filtering for metric

- projects/widgets/src/lib/widget-types/map/map.component.ts
> Hotfix map value

- .travis.yml
- projects/squacapi/src/lib/constants/monitor-options.constant.ts
- projects/squacapi/src/lib/types/monitor-types.type.ts
* remove Last N from select options
* remove Last N from squacapi module declarations
> Remove Last N From Monitor Options
